### ISSUE TITLE
Showing some error messages on NvimTree Close

### ISSUE THREAD

**Issue by melsonic** [nvim-tree/nvim-tree.lua#1962]
### Description

Some Error messages showing up when trying to close NvimTree when no file is opened

![error_nvimtree](https://user-images.githubusercontent.com/88551650/216084612-4938eb27-2379-40cd-bf83-46816cb2f35f.png)

### Neovim version

```text
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az190-151
```

### Operating system and version

Ubuntu 22.04

### nvim-tree version

215b29b

### Minimal config

```lua
this is the nvim-tree configuration file

`
-- disable netrw at the very start of your init.lua (strongly advised)
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

-- set termguicolors to enable highlight groups
vim.opt.termguicolors = true

-- empty setup using defaults
require("nvim-tree").setup()

-- OR setup with some options
require("nvim-tree").setup({
	sort_by = "case_sensitive",
	view = {
		adaptive_size = true,
		mappings = {
			list = {
				{ key = "u", action = "dir_up" },
			},
		},
	},
	renderer = {
		group_empty = true,
	},
	filters = {
		dotfiles = false
	},
})
`
```

### Steps to reproduce

1. open neovim 
2. open NvimTree (make sure no file is opened)
3. try to close NvimTree, then it will show some error messages

**Comment by tjex** [comment]
I was running this same NvimTree and Neovim version a few up until today and didn't ever have this issue. 
I am on a mac though. But that being said, your screenshot is from your user setup and not the temp setup right?

Can you confirm that this still happens when running Neovim along with the minimal config?

**Comment by tjex** [comment]
Ok. Regarding nvim not opening by default when launching at a directory, I also made an issue about that #1965 , and was pointed to read #1669 , which outlines it is no longer a default function and needs to be addressed on a user by user basis.

Are you sure it's creating a file called '.' though?
You can test by writing something and then trying to save, you should get an error saying that it can't be saved because it's a directory. You can see a screenshot of this in my issue, here again #1965 . 

But on the error on closing, I can't help much. Just trying to filter out options for the maintainer.

**Comment by melsonic** [comment]
@tjex ok, #1965 is the issue I'm talking about, I wasn't updated about that default behavior, but now it makes the whole sense. As you suggested I tried to save the file, and it prints `E502: "." is a directory. Again thanks for your precious time.

**Comment by alex-courtis** [comment]
The close failure is quite concerning; we are trying to close an apparently valid window.

Possibilities:
* some autowrite functionality is attempting to write the nvim-tree buffer
* another plugin or automation is intercepting the `nvim_win_close` events and introducing a problem

Confirming: are you running with an [nvt-min.lua](https://github.com/nvim-tree/nvim-tree.lua/issues/new?assignees=&labels=bug&template=bug_report.yml) or with your full nvim setup?

**Comment by luiz00martins** [comment]
For what is worth, I'm currently able to replicate this bug. In a fairly minimal setup (`nvim-tree` is the only plugin):
![image](https://user-images.githubusercontent.com/43142209/217066229-8ca4279a-0a6d-4947-8c0b-76537d6283c1.png)

**Comment by alex-courtis** [comment]
I can replicate this with those autocommands. I tried another arbitrarily selected plugin https://github.com/liuchengxu/vista.vim and it fails, differently.

`:copen` from an empty buffer will throw `E788: Not allowed to edit another buffer now` from the `BufWinEnter` au.

`mkview` failing seems reasonable, as there is no file name for the nvim-tree buffer.

I'm not sure what you're trying to do here; what is the purpose of those autocommands? With understanding we can resolve this.

**Comment by luiz00martins** [comment]
Apparently, it's something to do with folds: https://stackoverflow.com/questions/2142402/code-folding-is-not-saved-in-my-vimrc
I've removed them though, and haven't missed them since :)

I'm not sure if it's reasonable to expect it to fail, or if this is something that should be fixed. Just decided to leave the reason for my (similar) issue here, as it may help OP to debug his.

No real issues for me though.

**Comment by alex-courtis** [comment]
These autocommands need some filtering; they can't reasonably apply to all buffers i.e. not regular file buffers.

Closing this one as it is not nvim-tree specific.
