### ISSUE TITLE
Annoying error message after file deletion

### ISSUE THREAD

**Issue by festeh** [nvim-tree/nvim-tree.lua#2501]
### Description

Hi! 

Thanks for the awesome plugin! I have a small issue: Neovim produces an error [here](https://github.com/nvim-tree/nvim-tree.lua/blob/master/lua/nvim-tree/actions/fs/remove-file.lua#L35) (`Invalid buffer id: ...`) when I try to delete a file for which no buffer exists. I think buffer existence check should be added here (or maybe removing `force` option). It should be easy to fix, but of course I can make a PR. 

The case of the issue might be that I have a buffer auto-remove plugin (`hbac.nvim`), so it's probably not trivially reproducible, yet it should be simple to fix.

### Neovim version

```text
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux 6.2.0-34-generic

### nvim-tree version

78a9ca5

### Clean room replication

```lua
Delete a file using `d` key.
```

### Steps to reproduce

...

**Comment by alex-courtis** [comment]
> The case of the issue might be that I have a buffer auto-remove plugin (`hbac.nvim`), so it's probably not trivially reproducible, yet it should be simple to fix.

This is indeed not reproducible - delete failures like this are unacceptable.

Please provide ["Clean Room" Replication](https://github.com/nvim-tree/nvim-tree.lua/wiki/Troubleshooting#clean-room-replication) with the plugins you need to reproduce the issue so that we may fix it.

Alternatively, you could submit a [PR](https://github.com/nvim-tree/nvim-tree.lua/blob/master/CONTRIBUTING.md) to resolve this for your use case, dependent on no changes to current behaviour.
