### ISSUE TITLE
Is it not in the AUR?

### ISSUE THREAD

**Issue by dty2** [nvim-tree/nvim-tree.lua#2767]
Hey guys, I'm a arch user, and I want to install it from aur. And guess what, I can't find it in aur !!!
Is it my problem??? Tell me please...

**Comment by dty2** [comment]
sorry!!!! I find it ! Please check neovim tree not nvim tree!

**Comment by alex-courtis** [comment]
Today I learned of the existence of [neovim-tree-lua-git](https://aur.archlinux.org/packages/neovim-tree-lua-git) and [neovim-web-devicons-git](https://aur.archlinux.org/packages/neovim-web-devicons-git)

Dependencies are correct, with optional web-devicons, which has and mandatory ttf-font-nerd dependency.

AUR packaged neovim plugins are unorthodox but do work. Shame that they use `neovim-` prefix instead of `nvim-`.

Adding to installation doc.
