### ISSUE TITLE
nvim-tree can't display dotfiles in some cases

### ISSUE THREAD

**Issue by sincomil** [nvim-tree/nvim-tree.lua#2895]
### Description

When I run neovim with command line like: 
`nvim ~/DotFiles/NeoVIM/.config/nvim/init.lua`
and then use key binding to open nvim-tree on current file then I get into CWD directory where shell was when invoking a command to run neovim. If I close nvim-tree and repeat previous attempt then nvim-tree opening as it should.
But if I go up in nvim-tree to parent directory until directory containing .config directory with currently opened file then I can not get back because .config directory no longer displayed no matter of displaying dotfiles is enabled or not. The issue is recorded with [asciinema](https://asciinema.org/a/FVWvNwtHY4K0eMOsFqI5FWCCJ)

### Neovim version

```text
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1723675123
Run "nvim -V1 -v" for more info
```

### Operating system and version

6.10.7-arch1-1

### nvim-tree version

master, commit: ea55ef1

### Clean room replication

```lua
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "nvim-tree/nvim-tree.lua",
      "nvim-tree/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end

-- UNCOMMENT this block for diagnostics issues, substituting pattern and cmd as appropriate.
-- Requires diagnostics.enable = true in setup.
--[[
vim.api.nvim_create_autocmd("FileType", {
  pattern = "lua",
  callback = function()
    vim.lsp.start { cmd = { "lua-language-server" } }
  end,
})
]]
```

### Steps to reproduce

1. nvim -nu /tmp/nvt-min.lua ~/DotFiles/nvim-config/.config/nvim/init.lua
2. NvimTreeFindFileToggle
3. NvimTree appears with file tree in CWD before running STEP 1

### Expected behavior

 NvimTree have to appear with file opened focused on tree.

### Actual behavior

NvimTreeFindFileToggle does not do what it should do and completely ignores the file opened in current buffer. Also it is not possible to get into directory of currently opened file if that file is in directory  beginning with "." (dotfile directory)
Also recorded with [asciinema](https://asciinema.org/a/RcHC6rBxbiHdf9mRCqFmS5dGw)

**Comment by alex-courtis** [comment]
Thank you for the detailed reproduction.

RE step 2:

- Using a bang to update root may help you here: `:NvimTreeFindFileToggle!`
- That will update root, see `:help :NvimTreeFindFileToggle`
- It is preferable to use lua API as you have full control: `require("nvim-tree.api").tree.find_file({ open = true, update_root = true, })`

However, I don't think I'm seeing the real issue and can't reproduce this. Perhaps you could share your dotfiles so that we may properly reproduce.

**Comment by sincomil** [comment]
> * Using a bang to update root may help you here: `:NvimTreeFindFileToggle!`
This does not help :(


> * It is preferable to use lua API as you have full control: `require("nvim-tree.api").tree.find_file({ open = true, update_root = true, })`
Sadly but this is too  :(

Here is my simplified dotfiles directory that can reproduce this isssue
[nvim-dotfiles.zip](https://github.com/user-attachments/files/16944554/nvim-dotfiles.zip)

1. unpack it to /tmp/ 
2. open any file inside this dotfiles/ directory, example: `nvim /tmp/dotfiles/neovim/.config/nvim/lua/setup/core/keymaps.lua `

**Comment by alex-courtis** [comment]
I think that I'm misunderstanding "dotfiles". I am assuming now that you are literally talking about `dotfiles`, rather than files that begin with a `.`

Everything seems to be working as intended:

`nvim -nu nvt-min.lua /tmp/dotfiles/neovim/.config/nvim/lua/setup/core/keymaps.lua`
`:NvimTreeFindFileToggle` shows the current directory.

`:NvimTreeFindFileToggle!` shows `/tmp/dotfiles/neovim/.config/nvim/lua/setup/core`

You might want to take a look at [wiki/Open-At-Startup](https://github.com/nvim-tree/nvim-tree.lua/wiki/Open-At-Startup) for some recipes on how to change behaviour around nvim-tree directories at startup.
